### ISSUE TITLE
Double Star in Globs

### ISSUE THREAD

**Issue by pellebjerkestrand** [asbjornh/view-models#15]
It seems that using double stars in globs to match an arbitrary number of directories is unsupported.

Given f.ex. `client/**/*.jsx` as input, I would expect both `client/contexts/cool-context.jsx` and `client/components/cool-component/cool-component.jsx` to be processed.

There doesn't seem to be any documentation for the CLI, but using a single star to match filenames works fine. Using double stars matches a single directory, but not an arbitrary number of directories.

**Comment by asbjornh** [comment]
The CLI depends on the native expansion of globs which in turn would depend on your local environment. By default I don't think `bash` expands double stars in globs in the way you're describing. I'm not too keen on adding yet another dependency for this (since this package is already pretty dependency-heavy).

I guess this could be documented, and I could also add support for providing multiple paths

**Comment by asbjornh** [comment]
I've added documentation for the CLI that explains how paths work: https://github.com/asbjornh/view-models/blob/master/docs/cli.md. The CLI aleady supports providing multiple paths, so I'm going to close this :)
